### PR TITLE
Add sentry-servlet-jakarta for Java SDK

### PR DESCRIPTION
**Pull request by adinauer**

### CODE REVIEW

**Comment by marandaneto** [comment]
Let's merge it only after getting this version released.

**Comment by adinauer** [comment]
@marandaneto do you mean `6.0.0` or `6.0.0-alpha.6`?

**Comment by adinauer** [comment]
Merging now as `6.0.0-alpha.6` has been released

**Review by bruno-garcia — APPROVED** [review]

**Comment by bruno-garcia** [comment]
My approval doesn't help here. @mitsuhiko ?

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
