### PR TITLE
Add createdAt to all files

### PR DESCRIPTION
**Pull request by HazAT**
Big boy
context: https://github.com/getsentry/craft/pull/532

### CODE REVIEW

**Review by cleptric — CHANGES_REQUESTED** [review]
No newlines in the files now.

**Comment by HazAT** [comment]
@cleptric why do we need new lines?

**Comment by cleptric** [comment]
They have been there before, so not sure why we should remove them in the first place.

**Comment by szokeasaurusrex** [comment]
@HazAT text files (in UNIX at least) are defined as consisting of a series of lines, each ending in a newline character. Therefore, a non-empty test file that does not end in a newline is technically not a UNIX text file. [See here](https://unix.stackexchange.com/a/18789)

**Review by cleptric — APPROVED** [review]

**Pull request merged**
